# Generated by Django 3.2.5 on 2022-03-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(db_column='uid', primary_key=True, serialize=False, verbose_name='用户id')),
                ('userName', models.CharField(db_column='user_name', default='游客用户', max_length=20, verbose_name='用户名')),
                ('userDes', models.CharField(db_column='user_des', default='这个人很懒，没有留下简介', max_length=50, verbose_name='用户简介')),
                ('createDate', models.DateField(auto_now_add=True, db_column='create_date', verbose_name='用户注册时间')),
                ('authority', models.IntegerField(choices=[(0, 'Normal User'), (1, 'Admin')], db_column='authority', default=0, verbose_name='用户权限')),
                ('description', models.CharField(db_column='description', max_length=50, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('uid', models.OneToOneField(db_column='uid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='misback.user')),
                ('password', models.CharField(db_column='password', max_length=20)),
            ],
            options={
                'db_table': 'login_data',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pid', models.AutoField(db_column='pid', primary_key=True, serialize=False, verbose_name='检测项目id')),
                ('projectName', models.CharField(db_column='project_name', default='新项目', max_length=20, verbose_name='检测项目名称')),
                ('videoFile', models.CharField(db_column='video_file', max_length=50, verbose_name='检测项目文件名')),
                ('projectStatus', models.IntegerField(choices=[(0, 'Todo'), (1, 'Doing'), (2, 'Done')], db_column='project_status', default=0, verbose_name='检测项目当前状态, 0未启动, 1进行中, 2已完成')),
                ('description', models.CharField(db_column='description', max_length=50, null=True, verbose_name='备注')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='misback.user', verbose_name='检测项目所属用户')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
