# Generated by Django 3.2.5 on 2022-04-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='taskId',
            field=models.CharField(db_column='task_id', max_length=36, null=True, verbose_name='检测线程taskId'),
        ),
        migrations.AlterField(
            model_name='project',
            name='videoFile',
            field=models.CharField(db_column='video_file', max_length=50, verbose_name='检测项目文件名，保存路径为/media/<pid>_<projectName>/<videoFile>'),
        ),
    ]
